name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  #  MVS_PRODUCT: "utility"
  #  # The default release, should be overridden in config.sh
  #  MVS_RELEASE: "latest"
  #  # The default platform, should be overridden in the platform binaries jobs below
  #  MVS_PLATFORM: "linux"

  MVS_GPG_PASSWORD: ${{ secrets.MVS_GPG_PASSWORD }}
  MVS_REPO_USERNAME: ${{ secrets.MVS_REPO_USERNAME }}
  MVS_REPO_PASSWORD: ${{ secrets.MVS_REPO_PASSWORD }}

  DISPLAY: ":99"
  GITHUB_REF: ${{ github.ref }}
  # Needs to stay at a version compatible with all projects and the website
  JAVA_VERSION: "17"
  JAVA_DISTRO: "adopt"
  JAVA_PACKAGE: "jdk"
  MAVEN_PARMS: "-B -U -V --settings .github/settings.xml --file pom.xml"
  XVFB_PARMS: "-screen 0 1920x1080x24 -nolisten unix"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4

      - name: Fetch CI/CD resources
        uses: actions/checkout@v4
        with:
          repository: marksoderquist/cicd
          path: .github

      - name: Configuration
        shell: bash
        run: |
          source .github/config.sh

      # Required for tests
      - name: Set up Virtual Display
        run: |
          Xvfb ${{env.DISPLAY}} ${{env.XVFB_PARMS}} &

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{env.JAVA_VERSION}}

      - name: Maven Repository Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Compile
        run: |
          mvn ${{env.MAVEN_PARMS}} compile

      - name: Unit Tests
        run: |
          mvn ${{env.MAVEN_PARMS}} test

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Deploy Arifacts
        run: |
          mvn ${{env.MAVEN_PARMS}} deploy -Dmaven.test.skip=true

#      - name: Trigger Dependent Builds
#        run: |
#          curl -XPOST -u "${{secrets.MVS_CI_USERNAME}}:${{secrets.MVS_CI_PASSWORD}}" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/json" https://api.github.com/repos/marksoderquist/zarra/actions/workflows/ci.yml/dispatches --data '{"ref": "main"}'
#          curl -XPOST -u "${{secrets.MVS_CI_USERNAME}}:${{secrets.MVS_CI_PASSWORD}}" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/json" https://api.github.com/repos/marksoderquist/xenon-junit5/actions/workflows/ci.yml/dispatches --data '{"ref": "main"}'
#
#      - name: Deploy JavaDoc
#        run: |
#          ssh -t ${{env.MVS_REPO_USERNAME}}@avereon.com "mkdir -p ${{env.JAVADOC_DEPLOY_PATH}};"
#          if [ $? -ne 0 ]; then exit 1; fi
#          scp -B target/${MVS_PRODUCT}-*-javadoc.jar ${{env.MVS_REPO_USERNAME}}@avereon.com:${{env.JAVADOC_DEPLOY_PATH}}/javadoc.jar 2>&1
#          if [ $? -ne 0 ]; then exit 1; fi
#          ssh -t ${{env.MVS_REPO_USERNAME}}@avereon.com "mkdir -p ${{env.JAVADOC_TARGET_PATH}};rm -rf ${{env.JAVADOC_TARGET_PATH}}/*;unzip -o ${{env.JAVADOC_DEPLOY_PATH}}/javadoc.jar -d ${{env.JAVADOC_TARGET_PATH}}"
#          if [ $? -ne 0 ]; then exit 1; fi
